### PR TITLE
Fix handling of non-finite input for arb/acb_poly_compose_series

### LINKED ISSUE #1372: Change in behaviour when composing non-finite polynomials
The change to using the `gr_poly` methods for composition of polynomials changed the previous behavior for polynomials for which some, but not all, of the terms are non-finite. More precisely, for `arb_poly_compose_series` the lines
```C
    else if (!_arb_vec_is_finite(poly1, len1) || !_arb_vec_is_finite(poly2, len2))
    {
        _arb_vec_indeterminate(res, n);
    }
```
means that if any of the coefficients are non-finite then all of the coefficients in the output are indeterminate. The previous behavior was that if some of the higher order coefficients were non-finite then the lower order coefficients would still be finite. 

I have made heavy use of the previous behavior when computing Taylor series of functions which are not everywhere differentiable. In that case evaluation on a ball containing a non-differentiable point would give a finite result for the constant coefficient but a non-finite result for the next coefficient. This has been convenient because it allows for using higher order enclosures when the function is differentiable and fall back to direct enclosures when it is not differentiable. With the new behavior non-finite enclosures for the derivatives gives non-finite enclosures also for the constant coefficient.

I believe the easiest way to give the old behavior would be to in the above branch compute the index for the first non-finite coefficient and then compute the composition only up to that coefficient and set all the remaining coefficient to indeterminate values.

The story is similar for `acb_compose_series`, `arb_compose` and `acb_compose`.

### PR DESCRIPTION
**Pull request by Joel-Dahne**
If some higher coefficients in the input are non-finite it now computes finite values for the lower coefficients in the output instead of setting all coefficients in the output to non-finite values.

I added tests which I think should catch most mistakes I could have made.

This fixes #1372. 

Note that in the issue I say that this also affects `arb_poly_compose` and `acb_poly_compose`, this is not quite true. For those functions the constant term in the inner polynomial is in general non-zero and any non-finite coefficient in the outer polynomial thus gives a fully indeterminate result. The precise behavior for this before the change to use `gr_poly_compose` was dependent on which precise algorithm was used for computing the composition. For this reason I think it is fine to keep the current behavior of returning a fully indeterminate result for any non-finite input for these two functions.

### CODE REVIEW

File: src/acb_poly/compose_series.c [hunk 1]
```diff
@@ -23,7 +23,24 @@ _acb_poly_compose_series(acb_ptr res, acb_srcptr poly1, slong len1,
     }
     else if (!_acb_vec_is_finite(poly1, len1) || !_acb_vec_is_finite(poly2, len2))
     {
-        _acb_vec_indeterminate(res, n);
+        /* find k such that the first k coefficients of both poly1 and
+         * poly2 are finite */
+        slong k = 0;
+
+        while (acb_is_finite(poly1 + k) && acb_is_finite(poly2 + k))
```
Comment (fredrik-johansson) [inline src/acb_poly/compose_series.c:30]: I believe this can read out of bounds if one polynomial is shorter than the position of the first nonfinite coefficient in the other?

Comment (Joel-Dahne) [reply src/acb_poly/compose_series.c]: I think this should be fixed now! I also updated the tests so that they catch this.

**Comment by fredrik-johansson** [comment]
Thanks!
